import { Link } from 'react-router-dom';

export function About() {
  return (
    <div className="space-y-8 pb-20">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold tracking-tight text-gray-900">About This App</h1>
        <p className="text-lg text-gray-600">Unofficial Platform Advocate Tool.</p>
      </div>

      <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-200 space-y-6">
        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">What is this?</h2>
          <p className="text-gray-700">
            This is an unofficial advocacy tool designed to help supporters of Dave Messner for St. Louis County Assessor understand and share his platform accurately. It uses AI to summarize key points and generate respectful, neighborly content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">Who is Dave Messner?</h2>
          <p className="text-gray-700 mb-2">
            Dave is a Real Estate Professional, Eagle Scout, and small business owner running for St. Louis County Assessor. He holds an MBA from Washington University in St. Louis and brings significant experience in real estate appraisal, economic development (formerly with Greater St. Louis, Inc.), and community development.
          </p>
          <p className="text-gray-700">
            His campaign priorities are <strong>Fair Assessments</strong>, <strong>Proactive Service</strong>, <strong>Accurate Data</strong>, and a <strong>Transparent Process</strong>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">Source of Truth</h2>
          <p className="text-gray-700">
            All content generated by this app is based strictly on the publicly available platform text for Dave Messner.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">Disclaimer</h2>
          <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4">
            <p className="text-sm text-yellow-800">
              <strong>This app is NOT affiliated with, endorsed by, or paid for by the Dave Messner campaign.</strong> It is a volunteer-created tool for civic engagement.
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">Privacy</h2>
          <p className="text-gray-700">
            This app runs in your browser. We do not store your personal data or generated content on our servers.
          </p>
        </section>

        <div className="pt-6 border-t border-gray-100">
          <Link to="/" className="text-blue-600 hover:text-blue-800 font-medium">
            &larr; Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
